export interface QuizQuestion {
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export const quizQuestions: QuizQuestion[] = [
  { question: "Jaki procent tygodnia pracy to zadania powtarzalne, które AI może wykonać?", options: ["5-10%", "15-20%", "40-60%", "90-100%"], correct: 2, explanation: "Większość ludzi nie zdaje sobie sprawy, że 40-60% ich tygodnia to zadania powtarzalne delegowalne do AI." },
  { question: "Co to jest 'Matryca delegowania do AI'?", options: ["Arkusz Excel z formułami", "Podział zadań na 4 kategorie: AI 100%, AI+edycja, AI wspiera, Tylko Ty", "Lista narzędzi AI", "Harmonogram spotkań"], correct: 1, explanation: "Matryca pomaga zdecydować, które zadania delegować w pełni, częściowo, lub zostawić sobie." },
  { question: "Co oznacza 'R' w frameworku RICE dla AI?", options: ["Research", "Rola — kim ma być AI", "Result", "Revenue"], correct: 1, explanation: "RICE: Rola, Instrukcja, Kontekst, Efekt — framework do delegowania zadań AI." },
  { question: "Ile iteracji warto planować przy pracy z AI?", options: ["1 — pierwszy wynik jest zawsze idealny", "3 — draft → feedback → poprawka", "10 — im więcej, tym lepiej", "0 — nie trzeba iterować"], correct: 1, explanation: "Plan na 3 iteracje: AI generuje draft, Ty dajesz feedback, AI poprawia. To wciąż 5x szybciej niż pisanie od zera." },
  { question: "Co powinien zawierać system prompt firmowy?", options: ["Tylko nazwę firmy", "Kontekst firmy, zasady komunikacji, ograniczenia i ton głosu", "Listę konkurentów z cenami", "Dane finansowe firmy"], correct: 1, explanation: "System prompt firmowy = kontekst (firma, produkty, grupa) + zasady (ton, ograniczenia, format)." },
  { question: "Co to jest 'prompt chaining'?", options: ["Łańcuch e-maili", "Seria powiązanych promptów, gdzie wynik jednego jest wejściem do kolejnego", "Kopiowanie promptów", "Blokada AI"], correct: 1, explanation: "Prompt chaining: Research → Outline → Draft → Edycja → Finał. Każdy krok daje lepszy wynik niż mega-prompt." },
  { question: "Ile szablonów promptów warto mieć po miesiącu pracy z AI?", options: ["1-2", "5-10", "20-30", "100+"], correct: 2, explanation: "Po miesiącu dodawania 1 promptu dziennie masz 20-30 szablonów pokrywających 80% pracy." },
  { question: "Jakie elementy powinien mieć każdy wpis w bibliotece promptów?", options: ["Tylko tekst promptu", "Nazwa, cel, tekst, zmienne, przykład, ocena, tagi", "Data i godzina", "Tylko kategoria"], correct: 1, explanation: "Kompletny wpis: nazwa, cel, pełny tekst z zmiennymi [DO UZUPEŁNIENIA], przykład użycia, ocena i tagi." },
  { question: "Gdzie najlepiej trzymać bibliotekę promptów?", options: ["W pamięci", "Notion (baza danych z filtrami i tagami)", "Na karteczkach", "W historii chatu"], correct: 1, explanation: "Notion oferuje bazę danych z filtrami, tagami, sortowaniem — najlepsza opcja dla biblioteki promptów." },
  { question: "Co to jest 'batch processing' e-maili z AI?", options: ["Wysyłanie maili masowo", "Przetwarzanie wszystkich maili w jednym bloku czasowym zamiast reagowania na bieżąco", "Automatyczne kasowanie spamu", "Drukowanie maili"], correct: 1, explanation: "Batch processing = odpowiadanie na maile z AI w jednym bloku rano, zamiast reagowania na każdy mail osobno." },
  { question: "Jak AI może pomóc z notatkami ze spotkań?", options: ["Nie może — musi być człowiek", "Transkrypcja → wyciąganie action points, decyzji i podsumowań", "Tylko nagrywanie", "Wysyłanie zaproszeń"], correct: 1, explanation: "AI (Whisper/Otter.ai) transkrybuje, a ChatGPT wyciąga: podsumowanie, action points, decyzje, pytania otwarte." },
  { question: "Co AI może zrobić z arkuszem kalkulacyjnym?", options: ["Nic", "Pisać formuły, makra VBA, analizować dane, tworzyć wykresy", "Tylko otwierać pliki", "Tylko formatować komórki"], correct: 1, explanation: "AI pisze formuły Excel, tworzy makra VBA, analizuje trendy, czyści dane i generuje wizualizacje." },
  { question: "Co to jest workflow end-to-end?", options: ["Ręczne kopiowanie danych", "Automatyczny proces od wejścia do wyniku łączący wiele narzędzi", "Jeden prompt", "Arkusz Excel"], correct: 1, explanation: "Workflow end-to-end łączy wiele narzędzi w automatyczny proces: od wyzwalacza do końcowego wyniku." },
  { question: "Jakie narzędzie jest najlepsze na start do automatyzacji workflowów?", options: ["Pisanie kodu od zera", "Make.com lub Zapier (no-code)", "SAP", "Microsoft Paint"], correct: 1, explanation: "Make.com i Zapier oferują wizualne budowanie workflowów bez kodowania — idealny start." },
  { question: "Ile czasu zajmuje poranny rytuał planowania z AI?", options: ["60 minut", "10 minut", "2 godziny", "Cały dzień"], correct: 1, explanation: "10-minutowy poranny rytuał z AI: lista zadań → priorytetyzacja → bloki czasowe → plan dnia." },
  { question: "Co to jest matryca Eisenhowera w kontekście AI?", options: ["Typ modelu AI", "Podział zadań na pilne/ważne, który AI może zrobić za Ciebie", "Metoda szyfrowania", "Narzędzie do kodowania"], correct: 1, explanation: "AI priorytetyzuje Twoje zadania według matrycy Eisenhowera (pilne/ważne) na podstawie opisu." },
  { question: "Co to jest system PARA w Second Brain?", options: ["Typ procesora", "Projects, Areas, Resources, Archive — struktura organizacji wiedzy", "Program do AI", "Platforma e-commerce"], correct: 1, explanation: "PARA: Projects (aktywne), Areas (odpowiedzialności), Resources (materiały), Archive (zakończone)." },
  { question: "Jak AI pomaga w Second Brain?", options: ["Nie pomaga", "Przeszukuje notatki, łączy idee, streszcza, generuje wnioski", "Tylko przechowuje pliki", "Kasuje stare notatki"], correct: 1, explanation: "AI przeszukuje notatki, znajduje powiązania, streszcza artykuły i pomaga zamienić wiedzę w treści." },
  { question: "Jak obliczyć ROI z narzędzi AI?", options: ["Nie da się", "(Godziny zaoszczędzone × stawka godzinowa) - koszt narzędzi", "Liczba pobranych narzędzi", "Ilość wygenerowanych tekstów"], correct: 1, explanation: "ROI = oszczędności (godziny × stawka) minus koszty narzędzi. Mierz w PLN, nie w poczuciu." },
  { question: "Kiedy warto usunąć narzędzie AI ze stacka?", options: ["Nigdy", "Gdy koszt per użycie >$5 lub <4 użycia/miesiąc", "Po pierwszym dniu", "Gdy pojawi się nowsze"], correct: 1, explanation: "Audyt kwartalny: usuń narzędzia z niskim usage lub wysokim kosztem per użycie." },
  { question: "Jaki jest optymalny stack AI dla freelancera?", options: ["10+ narzędzi", "ChatGPT Plus + Canva Pro (~$33/mies)", "Tylko darmowe narzędzia", "Enterprise solutions"], correct: 1, explanation: "Minimalny, skuteczny stack: ChatGPT Plus (~$20) + Canva Pro (~$13) pokrywa treści i grafiki." },
  { question: "Co to jest 'tool fatigue'?", options: ["Zmęczenie fizyczne", "Pułapka subskrybowania wielu narzędzi, z których używasz kilka", "Awaria narzędzia", "Brak internetu"], correct: 1, explanation: "Tool fatigue = płacisz za 10 narzędzi, używasz 3. Rozwiązanie: kwartalny audyt i minimalizm." },
  { question: "Jak często warto robić audyt narzędzi AI?", options: ["Nigdy", "Co kwartał", "Codziennie", "Raz na 5 lat"], correct: 1, explanation: "Kwartalny audyt: sprawdź co używasz, co nie, jakie koszty — potrzeby się zmieniają." },
  { question: "Co jest ważniejsze: ilość narzędzi AI czy głębia opanowania?", options: ["Ilość — im więcej, tym lepiej", "Głębia — 3 narzędzia dobrze opanowane > 10 powierzchownie", "Oba równo", "Żadne — AI jest niepotrzebne"], correct: 1, explanation: "Jedno dobrze opanowane narzędzie daje więcej wartości niż pięć używanych powierzchownie." },
  { question: "Jaki jest najlepszy sposób na budowanie nawyku pracy z AI?", options: ["Przerobić cały kurs w 1 dzień", "Codziennie 1 nowe zastosowanie, 1 nowy prompt do biblioteki", "Czekać na idealne narzędzie", "Automatyzować wszystko naraz"], correct: 1, explanation: "Buduj nawyk stopniowo: 1 prompt dziennie, 1 nowe zastosowanie. Po miesiącu masz solidny system." },
  { question: "Co powinno być w tygodniowym review z AI?", options: ["Tylko lista zadań", "Analiza co poszło dobrze/źle, wnioski, plan na następny tydzień, nawyk do poprawienia", "Tylko pochwały", "Nic — review jest zbędny"], correct: 1, explanation: "Review = analiza + wnioski + plan + 1 nawyk do poprawienia + 1 rzecz do zautomatyzowania." },
  { question: "Ile czasu może zaoszczędzić dobrze zbudowany system pracy z AI?", options: ["30 minut/tydzień", "1-2h/tydzień", "10-20h/tydzień", "Nie oszczędza czasu"], correct: 2, explanation: "Dobrze skonfigurowany system (szablony + automatyzacje + Second Brain) oszczędza 10-20h tygodniowo." },
  { question: "Co jest kluczem do konsystentnych wyników z AI?", options: ["Zmiana modelu co tydzień", "Zarządzanie kontekstem — system prompts, pliki, projekty", "Pisanie krótszych promptów", "Ignorowanie wyników"], correct: 1, explanation: "Kontekst = konsystencja. System prompts, Custom Instructions i pliki kontekstowe dają spójne wyniki." },
  { question: "Dlaczego warto udostępniać szablony promptów zespołowi?", options: ["Nie warto", "Mnożysz oszczędność czasu — 1 szablon × 10 osób = 10x wartość", "Żeby się pochwalić", "Bo szef każe"], correct: 1, explanation: "Udostępnienie szablonów zespołowi mnoży wartość: jeśli szablon oszczędza 30 min, to dla 10 osób = 5h/tydzień." },
  { question: "Jaka jest najważniejsza zasada optymalizacji pracy z AI?", options: ["Używaj AI do wszystkiego", "Systematyczność: szablony, biblioteka, rutyny, audyty — system > chaos", "Nie używaj AI wcale", "Zmieniaj narzędzia co miesiąc"], correct: 1, explanation: "System > chaos. Szablony, biblioteka promptów, rutyny planowania i regularne audyty dają trwałe rezultaty." },
];
