export interface QuizQuestion {
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export const quizQuestions: QuizQuestion[] = [
  // ─── SEMESTR I: FUNDAMENTY (1-12) ─────────────
  { question: "Czym fundamentalnie jest Duży Model Językowy (LLM)?", options: ["Bazą danych przechowującą fakty z internetu", "Kalkulatorem prawdopodobieństwa przewidującym kolejne tokeny", "Świadomym algorytmem rozumiejącym logikę", "Silnikiem wyszukiwania"], correct: 1, explanation: "LLM to statystyczny model przewidujący kolejne tokeny na podstawie kontekstu." },
  { question: "Co to jest token w kontekście LLM?", options: ["Waluta subskrypcji", "Klucz API", "Pełne zdanie", "Część słowa lub znak — podstawowa jednostka przetwarzania"], correct: 3, explanation: "Token to fragment tekstu (subword), podstawowa jednostka obliczeniowa modelu." },
  { question: "Co oznacza RLHF w kontekście treningu modeli?", options: ["Rapid Learning from Huge Files", "Reinforcement Learning from Human Feedback", "Recursive Language for Handling Functions", "Real-time Learning from Historical Facts"], correct: 1, explanation: "RLHF to metoda fine-tuningu, gdzie ludzie oceniają odpowiedzi modelu." },
  { question: "Na jakiej architekturze opierają się nowoczesne LLM?", options: ["CNN (Convolutional Neural Network)", "RNN (Recurrent Neural Network)", "Transformer", "GAN (Generative Adversarial Network)"], correct: 2, explanation: "Architektura Transformer (2017, 'Attention Is All You Need') to fundament LLM." },
  { question: "Ile średnio tokenów to jedno słowo w języku polskim?", options: ["Dokładnie 1 token", "2-3 tokeny", "5-6 tokenów", "10 tokenów"], correct: 1, explanation: "Polska fleksja sprawia, że jedno słowo to zazwyczaj 2-3 tokeny." },
  { question: "Czym skutkuje Temperatura bliska 0.0?", options: ["Kreatywne, nieprzewidywalne odpowiedzi", "Model odmawia odpowiedzi", "Deterministyczne, powtarzalne odpowiedzi", "Szybsze generowanie tekstu"], correct: 2, explanation: "Temp 0.0 = model zawsze wybiera najbardziej prawdopodobny token." },
  { question: "Co to jest problem 'Lost in the Middle'?", options: ["Model zapomina ostatnie wiadomości", "Informacje w środku kontekstu są gorzej przetwarzane", "Model nie rozumie środkowych akapitów", "Środkowe tokeny kosztują więcej"], correct: 1, explanation: "Początek i koniec kontekstu przetwarzane lepiej niż środek." },
  { question: "Co robi parametr Top P = 0.1?", options: ["Model przetwarza 10% szybciej", "Model rozważa tylko 10% najprawdopodobniejszych tokenów", "Odpowiedź ma max 10% długości promptu", "10% szansy na odmowę odpowiedzi"], correct: 1, explanation: "Top P ogranicza pulę tokenów do tych o łącznym prawdopodobieństwie P." },
  { question: "Ile bloków budulcowych ma profesjonalny prompt?", options: ["2 (pytanie + odpowiedź)", "4 (rola, zadanie, kontekst, przykłady)", "6 (system, rola, kontekst, zadanie, przykłady, ograniczenia)", "10 (pełna specyfikacja)"], correct: 2, explanation: "6 bloków: System Prompt, Rola, Kontekst, Zadanie, Przykłady, Ograniczenia." },
  { question: "Jaka jest optymalna kolejność bloków w prompcie?", options: ["Zadanie → Rola → Kontekst → Ograniczenia", "Rola → Kontekst → Zadanie → Przykłady → Ograniczenia", "Ograniczenia → Zadanie → Rola → Kontekst", "Kolejność nie ma znaczenia"], correct: 1, explanation: "Rola ustawia 'mózg' modelu, ograniczenia na końcu = recency bias." },
  { question: "Czym są halucynacje AI?", options: ["Zbyt wolne generowanie", "Generowanie fałszywych informacji z dużą pewnością", "Odmowa wykonania polecenia", "Błąd tłumaczenia"], correct: 1, explanation: "Halucynacje = model pewnie generuje nieprawdziwe informacje." },
  { question: "Co oznacza 'zamrożona wiedza' modelu?", options: ["Model nie uczy się nowych języków", "Wiedza nie aktualizuje się po zakończeniu treningu", "Model działa w niskich temperaturach", "Model nie odpowiada o przyszłość"], correct: 1, explanation: "Po treningu model nie szuka nowych informacji — wiedza statyczna." },

  // ─── SEMESTR II: FRAMEWORKI (13-24) ────────────
  { question: "Co oznacza 'A' w frameworku CREATE?", options: ["Audience — grupa docelowa", "Algorithm — wybór modelu", "Answer — format odpowiedzi", "Action — krok po generowaniu"], correct: 0, explanation: "A = Audience, definiuje dla kogo przeznaczony jest wynik." },
  { question: "Czym framework RACE różni się od CREATE?", options: ["RACE ma więcej elementów", "RACE jest prostszy: Role, Action, Context, Expectation", "RACE jest tylko do kodu", "RACE nie wymaga roli"], correct: 1, explanation: "RACE to uproszczony wariant z 4 elementami." },
  { question: "Czym jest Zero-Shot Prompting?", options: ["Prompt z zerowym budżetem", "Prompt bez żadnych przykładów", "Prompt z zerową temperaturą", "Prompt z zerowym kontekstem"], correct: 1, explanation: "Zero-Shot = brak przykładów, model opiera się na treningu." },
  { question: "Czym jest Few-Shot Prompting?", options: ["Pisanie krótkich promptów", "Limitowanie do kilku słów", "Dostarczenie kilku przykładów pożądanych wyników", "Zadawanie kilku pytań naraz"], correct: 2, explanation: "Few-Shot = 3-5 przykładów wejście-wyjście w prompcie." },
  { question: "Najczęstszy błąd w Few-Shot?", options: ["Zbyt dużo przykładów", "Wszystkie przykłady zbyt podobne (brak edge cases)", "Przykłady w innym języku", "Numerowanie przykładów"], correct: 1, explanation: "Brak zróżnicowania = model nie uczy się obsługi wyjątków." },
  { question: "Ile przykładów zaleca się w Few-Shot?", options: ["1", "3-5", "10-20", "Im więcej, tym lepiej"], correct: 1, explanation: "3-5 to złoty standard — wystarczająco do wychwycenia wzorców." },
  { question: "Co robi Chain of Thought (CoT)?", options: ["Łączy modele AI w łańcuch", "Zmusza do rozpisania rozumowania krok po kroku", "Automatycznie tworzy łańcuch promptów", "Generuje odpowiedź w blokach"], correct: 1, explanation: "CoT = model rozpisuje kroki rozumowania przed odpowiedzią." },
  { question: "Jakie zdanie aktywuje Zero-Shot CoT?", options: ["'Odpowiedz krótko'", "'Let\\'s think step by step'", "'Bądź precyzyjny'", "'Wygeneruj najlepszą odpowiedź'"], correct: 1, explanation: "Magiczne zdanie zwiększające skuteczność z ~20% do 80%+." },
  { question: "O ile CoT zwiększa skuteczność w zadaniach logicznych?", options: ["Z 20% do ok. 40%", "Z 20% do ponad 80%", "Z 50% do 55%", "Brak mierzalnej różnicy"], correct: 1, explanation: "Badania Google Brain (2022) wykazały wzrost z ~20% do 80%+." },
  { question: "Czym Tree of Thought różni się od CoT?", options: ["ToT jest szybszy", "ToT eksploruje kilka równoległych ścieżek rozumowania", "ToT nie wymaga przykładów", "ToT działa tylko z GPT-4"], correct: 1, explanation: "ToT = wiele ścieżek → ocena → wybór najlepszej." },
  { question: "Na czym polega Self-Consistency?", options: ["Sprawdzanie gramatyki", "Rozwiązanie 3-5 razy, wybór najczęstszej odpowiedzi", "Porównanie dwóch modeli", "Spójność z promptem"], correct: 1, explanation: "Majority voting z wielu prób → redukuje halucynacje." },
  { question: "Kiedy CoT jest obowiązkowy?", options: ["Przy wierszach", "Przy tłumaczeniach", "Przy matematyce, logice, kodzie, analizie", "Przy grafikach"], correct: 2, explanation: "CoT kluczowy w wieloetapowym rozumowaniu." },

  // ─── SEMESTR III: ZAAWANSOWANE (25-32) ─────────
  { question: "Na czym polega Meta-Prompting?", options: ["AI pisze i optymalizuje prompty", "Używanie metadanych", "Prompting wielu modeli naraz", "Ukrywanie promptu"], correct: 0, explanation: "Meta-Prompting = AI tworzy i optymalizuje prompty." },
  { question: "Na czym polega Reverse Prompting?", options: ["Pisanie promptu od końca", "AI zadaje pytania użytkownikowi zamiast odpowiadać", "Odwracanie słów w prompcie", "Generowanie odwrotności odpowiedzi"], correct: 1, explanation: "AI wyciąga kontekst zadając pytania przed generowaniem." },
  { question: "Ile etapów ma Self-Refine?", options: ["1 (generowanie)", "2 (generowanie + krytyka)", "3 (generowanie + krytyka + poprawa)", "5 etapów"], correct: 2, explanation: "Self-Refine: Generuj → Krytykuj → Popraw." },
  { question: "Po ilu iteracjach Self-Refine jest optimum?", options: ["1", "2-3", "10+", "Nie ma limitu"], correct: 1, explanation: "2-3 iteracje to optimum. Więcej = marginalne zyski." },
  { question: "Co NIE jest elementem System Prompta?", options: ["Tożsamość i misja", "Reguły zachowania i zakazy", "Hasło do bazy danych", "Procedura eskalacji"], correct: 2, explanation: "System Prompt nie powinien zawierać wrażliwych danych." },
  { question: "Co to są Guardrails w System Prompcie?", options: ["Graficzne elementy UI czatu", "Zakazy i ograniczenia chroniące przed niepożądanym zachowaniem", "Szyny prowadzące prompt do odpowiedniego modelu", "Linie kodu zabezpieczające API"], correct: 1, explanation: "Guardrails = reguły czego AI NIE wolno robić." },
  { question: "Dlaczego głęboka Persona daje lepsze wyniki niż 'Jesteś ekspertem'?", options: ["Bo model się nudzi prostymi rolami", "Bo zawiera tło, motywacje i styl myślenia — model ma więcej kontekstu", "Bo dłuższy tekst = wyższa jakość", "Nie daje lepszych wyników — to mit"], correct: 1, explanation: "Głębsza persona = więcej kontekstu = lepsze dopasowanie odpowiedzi." },
  { question: "Kiedy Reverse Prompting jest najskuteczniejszy?", options: ["Przy prostych pytaniach", "Na początku projektu, gdy nie wiesz czego dokładnie potrzebujesz", "Przy generowaniu kodu", "Przy tłumaczeniach"], correct: 1, explanation: "Reverse Prompting pomaga zdefiniować potrzeby gdy cel jest niejasny." },

  // ─── SEMESTR IV: PRAKTYKA (33-40) ─────────────
  { question: "Na czym polega Prompt Chaining?", options: ["Łączenie wielu promptów w megaprompt", "Dzielenie zadania na sekwencję mniejszych promptów", "Powtarzanie tego samego promptu 5 razy", "Łączenie wyników z różnych modeli"], correct: 1, explanation: "Chaining = wyjście kroku N jest wejściem kroku N+1." },
  { question: "Dlaczego megaprompt (wszystko w jednym) jest gorszy?", options: ["Bo jest za długi i drogi", "Bo model dzieli uwagę między wiele zadań i obniża jakość każdego", "Bo API odrzuca długie prompty", "Bo trwa dłużej"], correct: 1, explanation: "Model dzieli 'uwagę' między zadania → spadek jakości." },
  { question: "Co to jest Gate Keeping w pipeline?", options: ["Blokowanie dostępu do API", "Walidacja jakości między krokami pipeline'u", "Sprawdzanie uprawnień użytkownika", "Ograniczanie tokenów wejściowych"], correct: 1, explanation: "Gate Keeping = sprawdzanie wyników przed kolejnym krokiem." },
  { question: "Które narzędzie NIE służy do automatyzacji pipeline'ów AI?", options: ["Zapier", "LangChain", "Photoshop", "Make.com"], correct: 2, explanation: "Photoshop to narzędzie graficzne, nie do automatyzacji AI." },
  { question: "Jaki jest anty-wzorzec nr 2 (negatywne ograniczenia)?", options: ["Pisanie zbyt długich promptów", "Mówienie 'nie rób X' zamiast 'rób Y'", "Używanie wielu języków", "Brak roli w prompcie"], correct: 1, explanation: "Sieci neuronowe źle reagują na negacje — mów CO robić, nie czego nie robić." },
  { question: "Co to jest Context Poisoning?", options: ["Celowe zatruwanie danych treningowych", "Wpływ poprzednich wiadomości na jakość kolejnych odpowiedzi w tym samym czacie", "Wysyłanie złośliwych promptów", "Przekroczenie limitu kontekstu"], correct: 1, explanation: "Nowe zadanie = nowy czat, bo stary kontekst zaśmieca odpowiedzi." },
  { question: "Co to jest Verbose Mode w debugowaniu?", options: ["Generowanie dłuższych odpowiedzi", "Prośba by AI wyjaśniło jak zinterpretowało Twoje polecenie", "Włączenie trybu głosowego", "Wyświetlanie tokenów w odpowiedzi"], correct: 1, explanation: "Verbose Mode pozwala zobaczyć, czy model dobrze zrozumiał prompt." },
  { question: "Ile razy profesjonalista iteruje prompt przed akceptacją?", options: ["1 raz (pierwszy prompt jest ostateczny)", "3-5 razy", "20+ razy", "Nie iteruje — używa szablonów"], correct: 1, explanation: "3-5 iteracji to standard profesjonalnego prompt engineeringu." },
];
