export interface QuizQuestion {
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export const quizQuestions: QuizQuestion[] = [
  // ─── SEMESTR I: PROJEKTOWANIE WORKFLOW (1-12) ─────────────
  { question: "Czym jest AI Workflow?", options: ["Pojedynczym promptem do ChatGPT", "Automatycznym ciągiem operacji wykonywanym krok po kroku", "Zbiorem danych treningowych dla modelu", "Bazą wektorową do wyszukiwania"], correct: 1, explanation: "AI Workflow to automatyczny proces, w którym AI wykonuje zadania sekwencyjnie lub równolegle." },
  { question: "Co jest pierwszym krokiem przed automatyzacją procesu w no-code?", options: ["Wybór modelu AI", "Napisanie kodu w Pythonie", "Zmapowanie i uporządkowanie ręcznego procesu", "Optymalizacja kosztów"], correct: 2, explanation: "Zanim zaczniesz automatyzować, musisz dokładnie zmapować proces i usunąć 'wąskie gardła'." },
  { question: "Do czego służy wyzwalacz (Trigger) w workflow?", options: ["Optymalizuje zużycie tokenów", "Generuje końcową odpowiedź", "Rozpoczyna (uruchamia) proces w odpowiedzi na zdarzenie", "Zatrzymuje proces w razie błędu"], correct: 2, explanation: "Wyzwalacz (Trigger) to zdarzenie inicjujące cały proces, np. odebranie nowego maila." },
  { question: "Jakie narzędzie no-code z reguły oferuje najbardziej wizualny interfejs do złożonych rozgałęzień?", options: ["Zapier", "Make.com", "LangChain", "OpenAI Playground"], correct: 1, explanation: "Make.com słynie z bardzo czytelnego, wizualnego edytora, który ułatwia tworzenie skomplikowanych rozgałęzień (routing)." },
  { question: "Czego NIE powinieneś robić przy projektowaniu workflow?", options: ["Automatyzować chaotycznego, niesprawdzonego procesu ręcznego", "Dzielić procesu na mniejsze kroki", "Rozważać przypadków brzegowych", "Używać narzędzi typu Miro do mapowania"], correct: 0, explanation: "Automatyzacja chaosu daje zautomatyzowany chaos. Zawsze najpierw uporządkuj proces ręczny." },
  { question: "Który moduł pozwala łączyć systemy, dla których nie ma gotowej integracji?", options: ["Router", "Webhook", "Iterator", "Aggregator"], correct: 1, explanation: "Webhooki pozwalają odbierać i wysyłać surowe żądania HTTP pomiędzy dowolnymi aplikacjami podłączonymi do sieci." },
  { question: "Dlaczego warto dzielić duże zadania dla AI na mniejsze kroki w workflow?", options: ["Aby zwiększyć koszty", "Aby zmniejszyć halucynacje i ułatwić debugowanie", "Bo pojedyncze API nie przyjmuje długich tekstów", "Nie ma żadnej różnicy"], correct: 1, explanation: "Podział zmniejsza złożoność i ryzyko pomyłki dla AI (model traci skupienie przy zbyt dużym jednorazowym zadaniu)." },
  { question: "Jak nazywamy miejsce w procesie, gdzie często dochodzi do opóźnień w ręcznej pracy?", options: ["Endpoint", "Wąskie gardło (Bottleneck)", "Trigger", "Router"], correct: 1, explanation: "Wąskie gardła to etapy procesu, które blokują lub spowalniają całą resztę operacji." },
  { question: "Co w systemach no-code oznacza warunek (Condition)?", options: ["Logika sterująca, która puszcza proces dalej tylko wtedy, gdy reguły są spełnione", "Ilość kredytów w planie", "Czas oczekiwania między krokami", "Długość promptu"], correct: 0, explanation: "Filtry / Warunki sprawiają, że workflow wykonuje się tylko dla określonych danych (np. tylko dla maili z załącznikiem)." },
  { question: "Jakie jest główne ograniczenie Zapier w porównaniu do n8n?", options: ["Brak integracji z Google", "Bardzo trudny interfejs kodowy", "Wysokie koszty przy dużej skali operacji", "Nie obsługuje ChatGPT"], correct: 2, explanation: "Zapier jest łatwy i posiada ogrom integracji, ale jego pakiety są kosztowne przy bardzo wielu wykonaniach (tasks/zaps)." },
  { question: "Z czym najlepiej radzi sobie model Gemini 1.5 Pro?", options: ["Generowanie obrazów wektorowych", "Analiza ogromnych ilości danych, książek i wideo", "Błyskawiczne API z najniższymi opóźnieniami dla chatbotów głosowych", "Pisanie najbardziej 'ludzkiego' copywritingu"], correct: 1, explanation: "Gemini 1.5 Pro ma okno kontekstowe na 1M-2M tokenów, co jest idealne dla ogromnych baz tekstów i nagrań." },
  { question: "Do czego wybitnie przydaje się Claude 3.5 Sonnet w workflows?", options: ["Obliczenia matematyczne z zakresu fizyki kwantowej", "Pisanie naturalnych tekstów, programowanie i analiza dużych bloków kodu", "Przeszukiwanie real-time Twittera", "Tworzenie animacji 3D"], correct: 1, explanation: "Claude 3.5 Sonnet to jeden z najpotężniejszych modeli do generowania świetnego copywritingu oraz tworzenia kodu." },

  // ─── SEMESTR II: ŁĄCZENIE WIELU AI (13-24) ────────────
  { question: "Dlaczego w workflow łączymy różne modele AI?", options: ["Ponieważ jedno konto w OpenAI to za mało", "Bo narzędzia no-code to wymuszają", "Każdy model ma inną specjalizację i uzyskujemy najwyższą jakość na każdym etapie", "Dla urozmaicenia faktur VAT"], correct: 2, explanation: "Różne zadania (np. matematyka, obrazy, copy) wymagają specyficznych modeli (np. GPT-4o, Midjourney, Claude)." },
  { question: "Co to jest Agent AI?", options: ["Fizyczny robot", "Człowiek obsługujący wsparcie klienta", "Mały, specjalistyczny model z jedną, konkretną rolą i promptem, współpracujący w procesie", "Narzędzie typu Zapier"], correct: 2, explanation: "Agent to spersonifikowany zestaw instrukcji dla LLM, skupiony na wąskim zadaniu, często potrafiący wywoływać narzędzia." },
  { question: "Co to jest 'Handoff' w kontekście modeli AI?", options: ["Przekazanie wyniku pracy z jednego modelu AI jako wejście do kolejnego modelu", "Wyłączenie modelu AI", "Zrzut błędów do pliku log", "Zwrot pieniędzy za API"], correct: 0, explanation: "Handoff to punkt w procesie, gdzie wyjście KROKU A staje się wejściem KROKU B (np. streszczenie przekazane do tłumacza)." },
  { question: "Jaki jest główny błąd przy zadawaniu złożonych ról w jednym prompcie (np. bądź SEO, Copywriterem i Grafikiem)?", options: ["Modele potrafią udawać tylko jedną postać na miesiąc", "Model dzieli 'uwagę' i wykonuje każde z tych zadań powierzchownie i słabo", "API odrzuca takie żądania", "Zwiększa to czas o 300%"], correct: 1, explanation: "Model skupiając się na zbyt wielu wytycznych jednocześnie, obniża precyzję. O wiele lepiej rozdzielić to na oddzielnych agentów." },
  { question: "Z czym najlepiej radzi sobie GPT-4o?", options: ["Generowanie długich artykułów SEO", "Logika, strukturyzacja danych, trzymanie się formatów JSON", "Analiza wideo godzinnych filmów na YouTube", "Klonowanie głosów"], correct: 1, explanation: "GPT-4o (oraz seria OpenAI) jest zazwyczaj najściślej trzymającym się struktur logiki i formatów JSON modelem na rynku." },
  { question: "Co oznacza 'Router LLM' w kontekście używania wielu modeli?", options: ["Sprzęt sieciowy dostarczany przez OpenAI", "Skrypt, który dynamicznie analizuje koszt i złożoność pytania, i wybiera odpowiedni model (np. mini lub pro)", "Panel administracyjny do wyłączania dostępu", "Baza danych z promptami"], correct: 1, explanation: "Router LLM decyduje na podstawie wejścia, czy do odpowiedzi potrzebny jest potężny i drogi model, czy wystarczy mniejszy i tańszy." },
  { question: "Który model wybralibyśmy zazwyczaj jako ostatecznego cenzora/redaktora jakości dla innych agentów?", options: ["Najtańszy i najszybszy model na rynku", "Model stricte przeznaczony do generowania obrazów", "Model najdroższy, o najwyższej precyzji logiki i wnioskowania (np. GPT-4o / Claude 3.5 Opus)", "Model z najmniejszym kontekstem"], correct: 2, explanation: "Agent oceniający innych (krytyk) musi mieć najwyższe zdolności reasoningowe, by wyłapać subtelne błędy i luki." },
  { question: "Jak wygląda koncepcja 'Self-Refine w grupie' (Synergia Agentów)?", options: ["Model wielokrotnie usuwa własne wiadomości z dysku", "Agenci mogą oceniać pracę innych agentów, tworząc zamkniętą pętlę podnoszenia jakości, zanim wynik trafi do użytkownika", "Model ignoruje polecenia użytkownika na rzecz własnych", "Zmuszenie użytkownika do pisania propozycji"], correct: 1, explanation: "Agent twórca generuje tekst, agent krytyk daje mu feedback, agent twórca poprawia." },
  { question: "Jeśli AI na końcu procesu musi wygenerować miniaturę posta, z jakim modelem powinieneś je połączyć?", options: ["Claude 3.5", "DALL-E 3 lub Midjourney (przez API)", "Gemini Flash", "Whisper"], correct: 1, explanation: "DALL-E i Midjourney to modele służące do syntezy i generowania obrazów." },
  { question: "Dlaczego testowanie promptów dla oddzielnych modeli jest tak istotne?", options: ["Aby dostać darmowe kredyty", "Bo Zapier nie pozwala zapisać zmian bez testu", "Bo każdy LLM ma inny 'styl' interpretacji poleceń i ten sam prompt może dać inne rezultaty na GPT i na Claude", "Bo to wymóg RODO"], correct: 2, explanation: "Modele różnych firm mają inne systemy bezpieczeństwa i pre-trening. Ten sam prompt do Claude może dać lepsze lub gorsze wyniki niż w GPT." },
  { question: "Kto powinien koordynować skomplikowany, wieloetapowy proces Multi-Agent?", options: ["Osoba klikająca ręcznie", "Wyzwalacz webhooka", "Jeden mały model klasyfikujący", "Zaprojektowany 'Agent-Menedżer' rozdzielający zadania poszczególnym sub-agentom"], correct: 3, explanation: "W architekturach agentowych (np. w CrewAI lub Autogen) nadrzędny agent analizuje główny cel i dyryguje pozostałymi agentami." },
  { question: "Co tracimy używając zawsze tylko jednego, wybranego modelu?", options: ["Czas działania", "Ryzykujemy niższym poziomem specjalizacji zadania i wyższymi kosztami w miejscach, w których tańszy model dałby radę", "Hasła do konta", "Dostęp do internetu"], correct: 1, explanation: "Brak dywersyfikacji powoduje overpaying na prostych zadaniach i niższą jakość w specjalistycznych (np. kodowanie vs pisanie wierszy)." },

  // ─── SEMESTR III: PIPELINE'Y PRZETWARZANIA (25-32) ─────────
  { question: "Czym charakteryzuje się przetwarzanie sekwencyjne w pipeline?", options: ["Zadania uruchamiają się naraz z wielu miejsc", "Krok B zawsze czeka na pełne wykonanie i wynik Kroku A", "Proces pomija błędy i idzie dalej", "Używa tylko jednego zapytania do bazy"], correct: 1, explanation: "Sekwencja to układ liniowy (1 -> 2 -> 3)." },
  { question: "Jakie przetwarzanie powinieneś wybrać, aby przetłumaczyć jeden tekst bazowy jednocześnie na 3 języki (EN, ES, DE)?", options: ["Przetwarzanie Sekwencyjne", "Ręczne kopiowanie", "Przetwarzanie Równoległe (Asynchroniczne)", "Przetwarzanie Rekursywne"], correct: 2, explanation: "Wykonanie 3 zapytań równolegle oznacza, że całość potrwa tyle co jedno, najdłuższe zapytanie, a nie suma 3 po kolei." },
  { question: "Do czego służy Gate Keeping?", options: ["Służy do generowania lepszych promptów dla grafików", "To walidacyjny punkt kontrolny sprawdzający, czy wynik spełnia kryteria jakości/formatu przed przekazaniem dalej", "Moduł do opłacania tokenów API", "Typ blokady w OpenAI na wrażliwe słowa"], correct: 1, explanation: "Gate Keeping broni proces przed 'kulą śnieżną błędów' przerywając go, jeśli dane są niepełne lub wadliwe." },
  { question: "Dlaczego format JSON jest tak pożądany jako wyjście Gate Keepingu?", options: ["Bo jest szyfrowany", "Łatwo na jego podstawie definiować i parsować zmienne (pola) w narzędziach takich jak Make czy Zapier", "Ponieważ zajmuje 10x mniej tokenów", "Ponieważ wygląda estetycznie w edytorach tekstu"], correct: 1, explanation: "Format JSON = strukturyzowane dane. System bez problemu wyłuska np. pole `status`, bez zgadywania i RegEx." },
  { question: "Czym jest 'Fallback' w obsłudze błędów procesu?", options: ["Sztuczką do przyspieszenia zapytań do API", "Procedurą awaryjną (zapasową) – uruchamianą w momencie awarii głównego systemu (np. użycie zapasowego modelu AI)", "Metodą uczenia modelu na własnych danych", "Zwróceniem błędu HTTP 500"], correct: 1, explanation: "Fallback zabezpiecza proces. Jeśli GPT-4 padnie, system woła Claude 3.5, żeby nie zepsuć workflow." },
  { question: "Co zrobisz, gdy serwer zwróci błąd '429 Too Many Requests' w trakcie działania Make.com?", options: ["Zatrzymam proces i wykasuję dane", "Skonfiguruję 'Retry' z opóźnieniem (np. po 1 minucie), ponieważ zjawisko jest tymczasowe", "Zgłoszę do OpenAI zablokowane konto", "Zmienię format odpowiedzi w prompcie"], correct: 1, explanation: "Błąd 429 oznacza przebicie limitu zapytań na minutę. Automatyczne ponawianie z opóźnieniem (backoff) ratuje proces." },
  { question: "Na czym polega zasada 'Default Values' w obsłudze błędów?", options: ["Zawsze podawaj swój adres domyślny przy płatności API", "Jeśli AI z jakiegoś powodu nie wyodrębni pożądanej danej, proces podstawi bezpieczną wartość domyślną i będzie działał dalej", "Ignorowanie błędów", "Wysyłanie e-maili do działu wsparcia za każdym razem"], correct: 1, explanation: "Aby system się nie zatrzymał na null/undefined, domyślna wartość (np. nazwa='Użytkownik') pozwala zachować ciągłość." },
  { question: "Jaki model najlepiej użyć do Gate Keepingu sprawdzającego skomplikowaną logikę?", options: ["Pojemnościowy, najtańszy model lokalny", "GPT-3.5 lub najtańszy darmowy model online", "Wysokiej klasy model oparty na logice, np. GPT-4o", "Model dedykowany tłumaczeniom językowym"], correct: 2, explanation: "Sprawdzanie logiki, przestrzegania instrukcji i formatu to zadania wymagające wysokich możliwości analizy, w czym przodują potężne modele." },

  // ─── SEMESTR IV: PRAKTYKA (33-40) ─────────────
  { question: "Dlaczego workflow działający dziś może nie zadziałać za 3 miesiące bez żadnej zmiany z Twojej strony?", options: ["Serwery OpenAI resetują się co kwartał", "Ponieważ modele AI (i ich API) są regularnie aktualizowane, a ich charakterystyka lub system restrykcji ulega zmianom (tzw. model drift)", "Narzędzia No-Code usuwają nieaktywne scenariusze", "Ponieważ w sieci nie ma nowych danych treningowych"], correct: 1, explanation: "Modele LLM otrzymują nowe wersje. Nawet stary checkpoint modelu ulega powolnej deprecjacji, a 'styl' bywa nieprzewidywalny bez monitoringu." },
  { question: "Do czego służy A/B Testing w workflow z użyciem LLM?", options: ["Do zmiany koloru przycisku w interfejsie bota", "Puszczania ruchu (np. maili wejściowych) na dwie różne wersje promptu i mierzenia, która daje większy wskaźnik poprawności lub lepsze wyniki sprzedaży", "Wyłącznie do sprawdzania, który LLM odpisuje szybciej o milisekundy", "Sprawdzania obciążenia dysku twardego"], correct: 1, explanation: "Testy A/B w kontekście LLM pozwalają ocenić i iterować nad jakością i skutecznością instrukcji w warunkach polowych." },
  { question: "Czym jest 'Golden Dataset' przy budowie AI Workflow?", options: ["Zestaw najdroższych tokenów do zakupienia z planu biznesowego", "Kolekcja starannie opracowanych przypadków testowych (np. 50 próbek wejścia), za pomocą których weryfikuje się, czy zmieniony prompt lub model nadal dobrze radzi sobie ze specyficznymi edge-case'ami", "Zbiór danych z wycieków sieciowych", "Nazwa najdroższego planu w Make.com"], correct: 1, explanation: "Golden Dataset to Twoja ostoja testowania: zanim wrzucisz zmiany na produkcję, upewniasz się, że Twój workflow przechodzi w 100% test na idealnych, sprawdzonych danych." },
  { question: "Kiedy wdrożyć mocną optymalizację kosztów (np. zmiana modelu na najtańszy)?", options: ["Na samym początku – liczy się każdy grosz", "W trakcie pisania promptu przed pierwszym testem", "Gdy workflow już działa, przyniósł efekty, i posiadamy zestawy testowe do zweryfikowania, czy zamiana na tańszy model drastycznie nie psuje wyników", "Gdy OpenAI wprowadzi nowy model i jest on za darmo"], correct: 2, explanation: "Optymalizuj koszty DOPIERO wtedy, gdy udowodnisz, że Twój proces biznesowy generuje wartość." },
  { question: "Co pozwala na używanie we workflow tańszego i 'głupszego' modelu (np. GPT-4o-mini) z dobrą skutecznością?", options: ["Zwiększanie temperatury na 1.0", "Poleganie wyłącznie na jego pretreningu", "Używanie bardzo długich instrukcji", "Dostarcznie mu wielu rygorystycznych przykładów Few-Shot (uczenie wejście-wyjście)", ], correct: 3, explanation: "Tańsze modele gorzej łapią subtelności z instrukcji systemowej, ale bardzo dobrze naśladują schematy i format z dostarczonych przykładów Few-Shot." },
  { question: "Na czym polega optymalizacja zmniejszania kontekstu w mailowym workflow?", options: ["Ucinanie pierwszej linijki z każdego wysłanego e-maila", "Odcinanie dołączonych podpisków prawnych, obrazków ze stopki, duplikatów poprzednich wątków i przesyłanie do LLM wyłącznie najnowszego komunikatu klienta", "Kodowanie całego maila do formatu Base64 przed wysłaniem", "Skasowanie wątku i odpowiedzenie generikiem"], correct: 1, explanation: "Każdy niepotrzebny element wysłany w tekście kosztuje tokeny, a ponadto 'rozmywa' wagę kluczowych zdań (attention dilution)." },
  { question: "Jak działa Buforowanie (Caching) w celu redukcji kosztów zapytania do AI?", options: ["Dane zapisywane są tylko na czas trwania scenariusza do RAM", "Użytkownik opłaca stałą miesięczną ratę za dostęp", "Jeśli zidentyfikowane zapytanie się powtarza (np. powtarzające się FAQ użytkownika), proces wyłapuje to, przerywa i pobiera gotową odpowiedź ze zwykłej bazy danych, bez dotykania API OpenAI", "Zmniejszany jest rozmiar promptu systemowego za każdym zapytaniem"], correct: 2, explanation: "Najtańszy LLM request to ten, który nigdy się nie odbywa. Częste, identyczne pytania idealnie rozwiązuje bufor z poprzednich sesji." },
  { question: "Jakie jest najczęstsze ryzyko zjawiska tzw. 'cichego błędu' (Silent Failure) w AI?", options: ["Model wypluwa czerwoną stronę z kodem błędu HTTPS", "Proces zakańcza się statusem OK 200, lecz wygenerowany tekst przez AI stopniowo gubi jakość, formatowanie i kluczowe niuanse bez alarmowania systemu", "Zbyt szybkie wysyłanie odpowiedź w czasie poniżej sekundy", "Całkowite zablokowanie konta"], correct: 1, explanation: "Dla no-code API wykonało zadanie, ale biznesowo odpowiedź to np. \"Przepraszam, jestem AI, nie pomogę\". Aby to wyłapać, potrzebny jest regularny audyt jakościowy." },
];
