export interface QuizQuestion {
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export const quizQuestions: QuizQuestion[] = [
  // ── MODUŁ I: FUNDAMENTY ──────────────────────────────
  { question: "Jakie zadania AI wykonuje najlepiej w firmie?", options: ["Negocjacje z klientami", "Powtarzalne, tekstowe, oparte na wzorcach", "Decyzje etyczne i prawne", "Zarządzanie zespołem"], correct: 1, explanation: "AI dominuje w zadaniach powtarzalnych, tekstowych i opartych na wzorcach — generowanie treści, analiza, klasyfikacja." },
  { question: "Co oznacza 'Zasada Pareto AI'?", options: ["AI działa tylko 20% czasu", "80% wartości z AI pochodzi z 20% zastosowań", "20% firm używa AI", "AI kosztuje 80% budżetu IT"], correct: 1, explanation: "Kluczem jest znalezienie 20% zastosowań, które dają 80% wartości — powtarzalne, czasochłonne procesy." },
  { question: "Czego NIE powinieneś delegować do AI?", options: ["Generowanie opisów produktów", "Decyzje o zwolnieniu pracownika", "Tłumaczenie dokumentów", "Streszczanie raportów"], correct: 1, explanation: "AI nie ponosi odpowiedzialności za decyzje etyczne i prawne — te muszą zostać podjęte przez człowieka." },
  { question: "Jaki jest wspólny wzorzec sukcesu firm wdrażających AI?", options: ["Wdrożenie AI we wszystkich procesach naraz", "Zatrudnienie zespołu AI na pełen etat", "Zaczęcie od JEDNEGO procesu, udowodnienie ROI, potem skalowanie", "Użycie najdroższego modelu AI"], correct: 2, explanation: "Najskuteczniejsze firmy zaczynają od jednego procesu, mierzą wyniki, a dopiero potem skalują." },
  { question: "Jaki jest 'Minimalny Stack AI' dla małego biznesu?", options: ["ChatGPT + Claude + Canva AI + Make.com", "Tylko ChatGPT", "SAP + Salesforce Einstein + Azure AI", "10 różnych specjalistycznych narzędzi"], correct: 0, explanation: "ChatGPT Plus + Claude Pro + Canva z AI + Make.com pokrywa treści, analizy, grafiki i automatyzacje za ~$60/mies." },
  { question: "Jak najlepiej mierzyć ROI z AI w firmie?", options: ["Liczbą zainstalowanych narzędzi", "Godzinami zaoszczędzonymi × stawka godzinowa", "Ilością wygenerowanych tekstów", "Zadowoleniem zespołu IT"], correct: 1, explanation: "ROI z AI = zaoszczędzone godziny × stawka godzinowa. To konkretna, mierzalna wartość." },

  // ── MODUŁ II: MARKETING I SPRZEDAŻ ──────────────────
  { question: "Co to jest 'Content Pipeline z AI'?", options: ["Rura do przesyłania danych", "Sekwencyjny proces: research → tworzenie → optymalizacja → dystrybucja → analiza", "Jedno narzędzie do marketingu", "Baza danych treści"], correct: 1, explanation: "Content Pipeline to systematyczny proces, w którym AI wspomaga każdy etap — od researchu po analizę wyników." },
  { question: "Ile kawałków contentu można stworzyć z jednego artykułu blogowego dzięki AI?", options: ["Tylko 1-2", "5-10", "Około 20 (posty, newsletter, stories, podcast, infografiki)", "Ponad 100"], correct: 2, explanation: "Recykling treści z AI: 1 artykuł → 10 postów social media, 1 newsletter, 5 stories, 1 podcast script, 3 infografiki." },
  { question: "Co jest kluczowe przy generowaniu wariantów reklamowych z AI?", options: ["Używanie jednego wariantu", "Generowanie minimum 10 wariantów i wybieranie najlepszych", "Kopiowanie reklam konkurencji", "Używanie tylko grafik AI"], correct: 1, explanation: "AI jest świetny w generowaniu ilości — Twoim zadaniem jest selekcja jakości z wielu wariantów." },
  { question: "Czym personalizacja cold outreach z AI różni się od mass mailingu?", options: ["Niczym", "AI tworzy spersonalizowane wiadomości dla każdego segmentu", "AI wysyła więcej maili", "Personalizacja jest droższa"], correct: 1, explanation: "AI umożliwia tworzenie spersonalizowanych wiadomości na skalę — lepsze niż 1 mail do wszystkich." },
  { question: "Co decyduje o 80% sukcesu posta na social media?", options: ["Hashtagi", "Hook — pierwsze zdanie", "Godzina publikacji", "Długość posta"], correct: 1, explanation: "Hook (pierwsze zdanie) decyduje czy ktoś zatrzyma się i przeczyta resztę." },
  { question: "Jaki jest optymalny system publikacji social media z AI?", options: ["Generuj i publikuj w tym samym dniu", "AI generuje propozycje z wyprzedzeniem, Ty edytujesz i planujesz", "Publikuj bez edycji", "Tylko ręczne tworzenie"], correct: 1, explanation: "Najlepszy system: AI generuje, Ty edytujesz (dodajesz swój głos), narzędzie automatycznie publikuje." },

  // ── MODUŁ III: OBSŁUGA KLIENTA I OPERACJE ──────────────
  { question: "Jaki procent zapytań klientów może obsługiwać AI bez udziału człowieka?", options: ["10%", "30%", "Około 80%", "100%"], correct: 2, explanation: "AI może obsługiwać ~80% typowych zapytań (FAQ, status zamówienia, cennik), eskalując resztę do człowieka." },
  { question: "Co powinien zawierać system prompt chatbota obsługi klienta?", options: ["Tylko nazwę firmy", "Instrukcje, bazę wiedzy, zasady eskalacji i ograniczenia", "Cennik konkurencji", "Hasła dostępowe"], correct: 1, explanation: "Dobry system prompt zawiera: zasady odpowiadania, bazę wiedzy, kiedy eskalować do człowieka i czego NIE robić." },
  { question: "Od jakiego poziomu automatyzacji obsługi klienta warto zacząć?", options: ["Poziom 3 — pełna automatyzacja", "Poziom 1 — FAQ Bot", "Poziom 2 — inteligentny asystent", "Wszystkie naraz"], correct: 1, explanation: "FAQ Bot daje 60% oszczędności przy minimalnym ryzyku — najlepszy punkt startu." },
  { question: "Co AI może zrobić z fakturą PDF?", options: ["Nic — nie czyta PDF-ów", "Przeczytać, wyciągnąć dane (kwota, NIP, data) i wpisać do arkusza", "Tylko wyświetlić", "Opłacić ją automatycznie"], correct: 1, explanation: "AI potrafi czytać PDF-y, rozpoznawać dane i strukturyzować je — idealne do przetwarzania faktur." },
  { question: "Jak AI pomaga w tworzeniu SOP-ów?", options: ["Nie pomaga", "Zamienia chaotyczny opis procesu w uporządkowaną, strukturalną procedurę", "Tylko drukuje dokumenty", "Zastępuje eksperta procesowego"], correct: 1, explanation: "AI strukturyzuje opis procesu, ale SOP tworzy ekspert z pomocą AI, nie AI samodzielnie." },
  { question: "Co jest kluczowe przy analizie umów z AI?", options: ["Bezwarunkowe zaufanie do wyników AI", "Weryfikacja wyników AI z prawnikiem", "Wysłanie umowy publicznie", "Ignorowanie sugestii AI"], correct: 1, explanation: "AI wskazuje potencjalne ryzyka w umowach, ale końcowa ocena prawna musi pochodzić od prawnika." },

  // ── MODUŁ IV: ANALITYKA, PRAWO, SKALOWANIE ──────────────
  { question: "Jak AI może pomóc w podejmowaniu decyzji biznesowych?", options: ["Podejmuje decyzje za Ciebie", "Analizuje dane, generuje wnioski i scenariusze 'what if'", "Tylko rysuje wykresy", "Nie nadaje się do analityki"], correct: 1, explanation: "AI analizuje dane i generuje scenariusze, ale decyzję podejmuje człowiek z kontekstem biznesowym." },
  { question: "Czego NIE wolno wrzucać do publicznych narzędzi AI?", options: ["Ogólnych pytań biznesowych", "Danych osobowych klientów, tajemnic handlowych, danych medycznych", "Prośb o tłumaczenie", "Pytań o formaty dokumentów"], correct: 1, explanation: "Dane osobowe, tajemnice handlowe, dane medyczne i finansowe NIE powinny trafiać do publicznych AI." },
  { question: "Co powinien zawierać dokument 'Polityka AI w firmie'?", options: ["Tylko listę narzędzi", "Dozwolone/zabronione zastosowania, procedury weryfikacji, odpowiedzialność, szkolenia", "Tylko kary za naruszenia", "Nic — AI nie wymaga polityki"], correct: 1, explanation: "Polityka AI powinna być kompleksowa: dozwolone użycia, ograniczenia, procedury, odpowiedzialności i szkolenia." },
  { question: "Co to jest AI Act?", options: ["Aplikacja mobilna", "Regulacja UE dotycząca systemów AI", "Firma technologiczna", "Typ modelu językowego"], correct: 1, explanation: "AI Act to regulacja Unii Europejskiej (od 2025) klasyfikująca systemy AI i nakładająca obowiązki na firmy." },
  { question: "Jak bezpiecznie używać AI z danymi firmowymi?", options: ["Wrzucać wszystko do darmowego ChatGPT", "Używać wersji enterprise/team, anonimizować dane", "Nie używać AI wcale", "Szyfrować dane ręcznie"], correct: 1, explanation: "Wersje enterprise (ChatGPT Team, Claude for Business) nie trenują modeli na Twoich danych + anonimizacja." },
  { question: "Jaki jest rekomendowany plan wdrożenia AI w firmie?", options: ["Wszystko w 1 tydzień", "30/60/90 dni: quick wins → rozbudowa → skalowanie", "12 miesięcy planowania bez działania", "Tylko jak budżet przekroczy 100k"], correct: 1, explanation: "Plan 30/60/90 dni: szybkie zwycięstwa, potem rozbudowa procesów, na końcu skalowanie i dokumentacja." },
  { question: "Ile może kosztować audyt AI dla klienta?", options: ["0 PLN — to darmowe", "50-100 PLN", "3000-10 000 PLN", "1 000 000 PLN"], correct: 2, explanation: "Audyt AI to wartościowa usługa — analiza procesów klienta i rekomendacje wdrożeń, wyceniana na 3000-10 000 PLN." },
  { question: "Co jest najważniejsze przy skalowaniu AI w firmie?", options: ["Kupowanie kolejnych narzędzi", "Dokumentacja procesów, szkolenie zespołu, mierzenie ROI", "Zatrudnienie specjalisty AI", "Ignorowanie bezpieczeństwa"], correct: 1, explanation: "Skalowanie = dokumentacja + szkolenia + metryki. Bez tego AI pozostanie zabawką, nie narzędziem biznesowym." },
  { question: "Jak sprzedawać usługi związane z AI?", options: ["Sprzedawaj 'AI' jako buzzword", "Sprzedawaj wynik: 'oszczędność 10h tygodniowo'", "Nie wyceniaj swoich usług", "Oferuj tylko darmowe konsultacje"], correct: 1, explanation: "Klienci nie kupują 'AI' — kupują wyniki: oszczędność czasu, pieniędzy, zwiększenie jakości." },
  { question: "Co jest najczęstszym błędem firm przy wdrażaniu AI?", options: ["Próba automatyzacji wszystkiego naraz", "Zaczynanie od małych projektów", "Mierzenie wyników", "Szkolenie zespołu"], correct: 0, explanation: "Najczęstszy błąd: próba wdrożenia AI wszędzie jednocześnie zamiast zaczęcia od 1-3 procesów." },
  { question: "Jaka jest rola człowieka w procesach z AI?", options: ["Żadna — AI robi wszystko", "Nadzór, weryfikacja, decyzje strategiczne i kontekst biznesowy", "Tylko włączanie i wyłączanie AI", "Pisanie kodu dla AI"], correct: 1, explanation: "Człowiek = nadzorca, weryfikator i decydent. AI = asystent wykonujący powtarzalne zadania." },
];
