export interface QuizQuestion {
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export const quizQuestions: QuizQuestion[] = [
  { question: "Co jest kluczowe przy dostosowywaniu promptu z kolekcji?", options: ["Kopiowanie bez zmian", "Uzupełnienie zmiennych [DO UZUPEŁNIENIA] swoimi danymi i kontekstem", "Usunięcie wszystkich instrukcji", "Zmiana języka na angielski"], correct: 1, explanation: "Prompt z kolekcji to szablon — uzupełniasz zmienne swoim kontekstem, dostosowujesz ton i styl." },
  { question: "Jakie elementy ma każdy prompt w kolekcji?", options: ["Tylko tekst", "Rola, instrukcja, kontekst (zmienne), format wyjścia", "Tylko pytanie", "Kod programistyczny"], correct: 1, explanation: "Anatomia promptu: ROLA (kim jest AI), INSTRUKCJA (co robi), KONTEKST (zmienne), FORMAT (jak wygląda wynik)." },
  { question: "Co daje największy wpływ na jakość promptu?", options: ["Długość promptu", "Rola + kontekst = 80% jakości", "Użycie emoji", "Powtórzenie słów"], correct: 1, explanation: "Rola (kim jest AI) i kontekst (branża, grupa, cel) decydują o 80% jakości odpowiedzi." },
  { question: "Dlaczego warto podawać przykład oczekiwanego wyniku w prompcie?", options: ["Nie warto", "AI uczy się przez naśladowanie — przykład definiuje standard jakości", "Zajmuje to zbyt dużo miejsca", "AI ignoruje przykłady"], correct: 1, explanation: "Przykład to najskuteczniejszy sposób komunikacji z AI — pokazujesz czego oczekujesz zamiast opisywać." },
  { question: "Ile kategorii powinien mieć system organizacji biblioteki promptów?", options: ["1-2", "5-8 głównych z podkategoriami", "50+", "Nie potrzeba kategorii"], correct: 1, explanation: "5-8 głównych kategorii (Biznes, Marketing, Sprzedaż, Operacje, Kreatywność, Analiza, HR) z podkategoriami." },
  { question: "Co to jest zasada 80/20 w bibliotece promptów?", options: ["80% promptów jest złych", "80% pracy pokrywa 20% promptów — to Twoje TOP 10 'Favorites'", "Używaj 80% czasu na tworzenie", "20% to wystarczająca ilość"], correct: 1, explanation: "80% codziennej pracy pokrywa 20% promptów. Zidentyfikuj i oznacz swoje TOP 10 jako Favorites." },
  { question: "Jak często aktualizować bibliotekę promptów?", options: ["Nigdy", "Co piątek 10 min przegląd, co 2 tygodnie aktualizacja ocen", "Raz w roku", "Codziennie 2h"], correct: 1, explanation: "Cotygodniowy 10-min przegląd + aktualizacja co 2 tygodnie + kwartalny duży przegląd." },
  { question: "Co to jest prompt chaining?", options: ["Łańcuch maili", "Seria promptów, gdzie wynik jednego jest wejściem następnego", "Blokada AI", "Kopiowanie promptu"], correct: 1, explanation: "Prompt chaining: Research → Outline → Draft → Edit. Każdy krok używa wyniku poprzedniego jako input." },
  { question: "Ile przykładów warto podać w technice few-shot?", options: ["0", "1", "3-5", "50+"], correct: 2, explanation: "3 przykłady to minimum, 5 to ideał. AI potrzebuje wzorców do naśladowania." },
  { question: "Co daje technika Chain-of-Thought?", options: ["Szybsze odpowiedzi", "Lepsze rozumowanie — AI rozpisuje kroki zamiast zgadywać", "Mniejsze koszty", "Krótsze odpowiedzi"], correct: 1, explanation: "Chain-of-Thought zmusza AI do rozpisania kroków rozumowania, co drastycznie poprawia jakość w złożonych zadaniach." },
  { question: "Jak działa roleplaying w promptach?", options: ["AI udaje robota", "Nadajesz AI konkretną rolę z cechami, doświadczeniem i stylem odpowiadania", "AI odmawia odpowiedzi", "To technika programistyczna"], correct: 1, explanation: "Im bardziej szczegółowa rola (doświadczenie, cechy, styl), tym lepsze i bardziej specjalistyczne odpowiedzi." },
  { question: "Co jest lepsze: mega-prompt czy prompt chaining?", options: ["Mega-prompt zawsze lepszy", "Prompt chaining — krótsze, skupione kroki dają wyższą jakość", "Oba równe", "Żaden — lepiej nie używać AI"], correct: 1, explanation: "Prompt chaining dzieli złożone zadanie na mniejsze kroki — każdy krok daje lepszy wynik niż próba zrobienia wszystkiego naraz." },
  { question: "Ile promptów warto mieć po 3 miesiącach budowania kolekcji?", options: ["5-10", "15-20", "50+", "500+"], correct: 2, explanation: "Cel: 50+ przetestowanych promptów po 3 miesiącach — pokrywa ~90% codziennej pracy." },
  { question: "Co jest najcenniejszą częścią biblioteki promptów?", options: ["Ilość promptów", "Oceny i notatki o tym CO działa i CO nie", "Kolorowe tagi", "Nazwy promptów"], correct: 1, explanation: "Oceny (1-5★) i notatki (co działa, z jakim modelem, co poprawić) to wiedza, której nie kupisz." },
  { question: "Jaka jest najlepsza baza do przechowywania biblioteki promptów?", options: ["Pamięć", "Notion (baza danych z filtrami, tagami, sortowaniem)", "Karteczki samoprzylepne", "Historia chatu"], correct: 1, explanation: "Notion oferuje bazę danych z filtrami, tagami, wyszukiwaniem i widokami — idealne do biblioteki promptów." },
  { question: "Co powinien zawierać prompt do analizy SWOT z AI?", options: ["Tylko nazwę firmy", "Opis firmy, branżę, rynek + prośbę o min. 5 punktów per element z uzasadnieniem", "Tylko pytanie 'Zrób SWOT'", "Dane finansowe"], correct: 1, explanation: "Im więcej kontekstu (firma, branża, rynek, konkurencja), tym trafniejsza analiza SWOT." },
  { question: "Jak AI pomaga w cold email?", options: ["Wysyła maile automatycznie", "Generuje spersonalizowane warianty (pain point, social proof, pytanie)", "Hakuje skrzynki pocztowe", "Nie pomaga w mailach"], correct: 1, explanation: "AI generuje warianty cold email: wersja pain point, social proof, pytanie — testujesz i mierzysz wyniki." },
  { question: "Co jest kluczowe w prompcie na landing page?", options: ["Długość tekstu", "Sekcje: hero, problem, rozwiązanie, korzyści, social proof, FAQ, CTA", "Użycie wielu kolorów", "Tylko cena"], correct: 1, explanation: "Skuteczny landing page ma strukturę: hook → problem → rozwiązanie → korzyści → dowody → CTA." },
  { question: "Jak generować pomysły z AI (brainstorming)?", options: ["Prosić o 1 pomysł", "Generować 20 pomysłów w 4 kategoriach: bezpieczne, kreatywne, szalone, hybrydowe", "Kopiować pomysły konkurencji", "AI nie umie brainstormować"], correct: 1, explanation: "20 pomysłów w 4 kategoriach ryzyka daje pełne spektrum — od bezpiecznych po innowacyjne." },
  { question: "Co daje prompt do SOP (Standard Operating Procedure)?", options: ["Nic przydatnego", "AI zamienia chaotyczny opis procesu w uporządkowaną procedurę z krokami i checkboxami", "Tylko listę narzędzi", "Regulamin firmy"], correct: 1, explanation: "AI strukturyzuje opis procesu w: cel, zakres, kroki z checkboxami, wyjątki, metryki — gotowy SOP w 5 min." },
  { question: "Jak używać AI do analizy danych w Excelu?", options: ["Nie da się", "Wgrać dane + opisać co chcesz osiągnąć → AI pisze formuły i analizuje", "Tylko do prostego sumowania", "Trzeba znać Python"], correct: 1, explanation: "Opisujesz dane i cel → AI pisze formuły Excel, makra VBA, analizuje trendy i generuje wnioski." },
  { question: "Ile branżowych pakietów promptów zawiera ta kolekcja?", options: ["1", "3", "6 (Marketing, E-commerce, HR, Finanse, Edukacja, Social Media)", "20"], correct: 2, explanation: "Kolekcja zawiera pakiety dla 6 branż: Marketing & Reklama, E-commerce & Sprzedaż, HR & Rekrutacja, Finanse & Analityka, Edukacja & Szkolenia, Social Media & Content." },
  { question: "Jaki jest minimalny czas oszczędności per prompt, aby był wart zachowania?", options: ["1 sekunda", "5 minut per użycie", "2 godziny", "1 dzień"], correct: 1, explanation: "Każdy prompt w bibliotece powinien oszczędzać minimum 5 minut per użycie — przy 10 użyciach to prawie godzina." },
  { question: "Co robić z promptem, który ma ocenę poniżej 3 gwiazdek?", options: ["Zostawić", "Usunąć lub poprawić (dodać kontekst, przykłady, ograniczenia)", "Ignorować oceny", "Dać mu więcej czasu"], correct: 1, explanation: "Prompty z oceną <3★ po 3 użyciach: popraw (więcej kontekstu, przykładów) lub usuń z biblioteki." },
  { question: "Dlaczego warto udostępniać bibliotekę promptów zespołowi?", options: ["Nie warto", "1 prompt × 10 osób = 10x wartość — mnożysz oszczędność czasu", "Żeby się pochwalić", "Bo szef każe"], correct: 1, explanation: "Udostępnienie szablonów zespołowi mnoży wartość: szablon oszczędzający 30 min × 10 osób = 5h/tydzień." },
  { question: "Co to są 'ograniczenia' w prompcie i dlaczego są ważne?", options: ["Limity techniczne AI", "Instrukcje czego AI ma UNIKAĆ — równie ważne jak instrukcje co robić", "Długość odpowiedzi", "Cena API"], correct: 1, explanation: "Ograniczenia ('NIE używaj żargonu', 'UNIKAJ strony biernej') są tak samo ważne jak instrukcje pozytywne." },
  { question: "Jaki jest najlepszy sposób na testowanie nowego promptu?", options: ["Użyć raz i ocenić", "Przetestować 3 razy, w różnych kontekstach, na różnych modelach", "Nie testować — od razu używać", "Testować przez miesiąc"], correct: 1, explanation: "3 testy w różnych kontekstach i na różnych modelach (GPT, Claude) dają rzetelną ocenę jakości promptu." },
  { question: "Co jest lepsze: korzyści czy cechy w opisie produktu?", options: ["Cechy", "Korzyści — 'Oszczędź 2h dziennie' > 'Procesor 3.5 GHz'", "Oba równo", "Ani jedno, ani drugie"], correct: 1, explanation: "Klienci kupują korzyści, nie cechy. 'Oszczędź 2h dziennie' jest silniejsze niż 'Procesor 3.5 GHz'." },
  { question: "Jak traktować swoją kolekcję promptów?", options: ["Jako zabawkę", "Jako aktywo biznesowe warte setki zaoszczędzonych godzin", "Jako obowiązek", "Jako tymczasowe rozwiązanie"], correct: 1, explanation: "Kolekcja promptów to Twoja przewaga konkurencyjna — traktuj ją jak aktywo generujące wartość." },
  { question: "Co jest najważniejszą zasadą przy korzystaniu z kolekcji promptów?", options: ["Kopiuj bez zmian", "Dostosuj, testuj, iteruj — prompt to punkt startu, nie gotowy produkt", "Używaj tylko jednego promptu", "Zmieniaj prompt co dzień"], correct: 1, explanation: "Prompt z kolekcji to punkt startu. Kluczem jest: dostosowanie do kontekstu, testowanie i iteracja." },
];
