export interface QuizQuestion {
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export const quizQuestions: QuizQuestion[] = [
  // ─── SEMESTR I: ZAAWANSOWANE ROZUMOWANIE (1-8) ─────
  { question: "Co to jest Chain-of-Thought (CoT)?", options: ["Łączenie wielu modeli AI w łańcuch", "Technika zmuszająca model do rozpisania kroków rozumowania", "Automatyczne tworzenie łańcucha promptów", "Metoda trenowania modeli"], correct: 1, explanation: "CoT zmusza model do pokazania kroków rozumowania przed podaniem odpowiedzi." },
  { question: "Jakie zdanie aktywuje Zero-Shot CoT?", options: ["'Odpowiedz krótko i precyzyjnie'", "'Let's think step by step'", "'Bądź ekspertem w tej dziedzinie'", "'Wygeneruj najlepszą odpowiedź'"], correct: 1, explanation: "\"Let's think step by step\" aktywuje tryb rozumowania bez przykładów." },
  { question: "O ile CoT zwiększa skuteczność w zadaniach logicznych?", options: ["Z 50% do 55%", "Z 20% do ponad 80%", "Z 80% do 85%", "Brak mierzalnej różnicy"], correct: 1, explanation: "Badania Google Brain (2022) wykazały wzrost z ~20% do 80%+." },
  { question: "Czym Structured CoT różni się od zwykłego CoT?", options: ["Jest szybszy", "TY definiujesz konkretne etapy analizy zamiast polegać na modelu", "Wymaga mniej tokenów", "Działa tylko z GPT-4"], correct: 1, explanation: "Structured CoT narzuca framework analizy — model przechodzi przez zdefiniowane kroki." },
  { question: "Ile przykładów to 'złoty standard' w Few-Shot?", options: ["1", "3-5", "10-15", "Im więcej tym lepiej"], correct: 1, explanation: "3-5 przykładów wystarczy do wychwycenia wzorca bez marnowania tokenów." },
  { question: "Która zasada jest NAJWAŻNIEJSZA w Few-Shot?", options: ["Maksymalna liczba przykładów", "Różnorodność przykładów i edge cases", "Przykłady w języku angielskim", "Krótkie przykłady"], correct: 1, explanation: "Różnorodność > Ilość. Edge cases pokazują modelowi jak obsługiwać trudne przypadki." },
  { question: "Co oznacza 'konsystentny format' w Few-Shot?", options: ["Wszystkie przykłady mają identyczną strukturę", "Przykłady są napisane tym samym językiem", "Każdy przykład ma tę samą długość", "Przykłady dotyczą tego samego tematu"], correct: 0, explanation: "Niespójny format (np. różne separatory) myli model i pogarsza wyniki." },
  { question: "Kiedy NIE warto używać CoT?", options: ["Przy matematyce", "Przy prostych zadaniach jak tłumaczenie czy korekta", "Przy debugowaniu kodu", "Przy analizie danych"], correct: 1, explanation: "Proste jednokrokowe zadania nie wymagają rozumowania — CoT to niepotrzebny overhead." },

  // ─── SEMESTR II: ROLE, KONTEKST, ToT (9-16) ────────
  { question: "O ile role prompting zwiększa jakość odpowiedzi?", options: ["1-5%", "15-30% dla domain-specific tasks", "50-80%", "Nie ma mierzalnego wpływu"], correct: 1, explanation: "Badania pokazują 15-30% wzrost jakości dla zadań specjalistycznych." },
  { question: "Co daje 'głęboka persona' w porównaniu z 'Jesteś ekspertem'?", options: ["Nic — to mit", "Więcej kontekstu (doświadczenie, wartości, styl) = lepsze dopasowanie", "Tylko dłuższą odpowiedź", "Wyższe koszty bez korzyści"], correct: 1, explanation: "Głębsza persona dostarcza więcej kontekstu, co prowadzi do trafniejszych odpowiedzi." },
  { question: "Czym jest Multi-Persona prompting?", options: ["Rozmowa z wieloma modelami AI", "Analiza z wielu perspektyw (np. CTO, CFO, CMO) w jednym prompcie", "Zmiana roli w trakcie konwersacji", "Tworzenie avatarów AI"], correct: 1, explanation: "Multi-Persona daje kilka perspektyw w jednym prompcie — np. technologiczna, finansowa, marketingowa." },
  { question: "Co to jest Context Poisoning?", options: ["Celowe zatruwanie danych treningowych", "Wpływ poprzednich wiadomości na jakość kolejnych odpowiedzi", "Wysyłanie złośliwych promptów", "Przekroczenie limitu kontekstu"], correct: 1, explanation: "Stary kontekst 'zaśmieca' nowe odpowiedzi. Rozwiązanie: nowe zadanie = nowy czat." },
  { question: "Jak działa hierarchiczne filtrowanie kontekstu?", options: ["Filtruje po dacie", "Dzieli informacje na MUST HAVE / NICE TO HAVE / IGNORUJ", "Sortuje kontekst alfabetycznie", "Kasuje duplikaty"], correct: 1, explanation: "3-poziomowy filtr priorytetyzuje informacje dla modelu." },
  { question: "Czym Tree-of-Thoughts różni się od CoT?", options: ["ToT jest szybszy", "ToT eksploruje wiele równoległych ścieżek rozumowania", "ToT nie wymaga promptu", "ToT działa offline"], correct: 1, explanation: "CoT = jedna ścieżka liniowa. ToT = wiele ścieżek → ocena → wybór najlepszej." },
  { question: "Kiedy ToT jest overkill?", options: ["Przy decyzjach high-stakes", "Gdy jest jedno oczywiste rozwiązanie", "Przy kreatywnych problemach", "Gdy chcesz zobaczyć trade-offs"], correct: 1, explanation: "Gdy rozwiązanie jest oczywiste, ToT to strata tokenów i czasu." },
  { question: "Co dodaje scoring system w ToT?", options: ["Szybkość generowania", "Obiektywne porównanie opcji przez wagi i punkty", "Lepszą gramatykę", "Więcej opcji"], correct: 1, explanation: "Scoring z wagami obiektywizuje decyzję — model oblicza ważone sumy i rekomenduje zwycięzcę." },

  // ─── SEMESTR III: AGENCI, META, MULTIMODAL (17-22) ──
  { question: "Co oznacza ReAct?", options: ["Reactive Action", "Reasoning + Acting naprzemiennie", "Real-time Action Control", "Recursive Action"], correct: 1, explanation: "ReAct = Thought → Action → Observation → Thought → ... w pętli." },
  { question: "Dlaczego ReAct jest lepszy niż 'pure reasoning'?", options: ["Jest tańszy", "Model może działać (szukać, obliczać) a nie tylko myśleć", "Generuje mniej tokenów", "Nie wymaga promptu"], correct: 1, explanation: "Pure reasoning = myślenie bez narzędzi. ReAct łączy myślenie z konkretnymi akcjami." },
  { question: "Co to jest Meta-Prompting?", options: ["Prompting o metadanych", "Proszenie AI o stworzenie lub ulepszenie promptu", "Ukrywanie promptu przed użytkownikiem", "Prompting wielu modeli naraz"], correct: 1, explanation: "Meta-Prompting = AI projektuje prompty, bo 'wie' co działa best dla jego architektury." },
  { question: "Na czym polega Reverse Prompting?", options: ["Pisanie promptu od końca", "AI zadaje pytania użytkownikowi zanim zacznie pracować", "Odwracanie kolejności słów", "Generowanie odwrotnej odpowiedzi"], correct: 1, explanation: "AI zadaje pytania, żeby lepiej zrozumieć potrzeby — idealne na początku projektu." },
  { question: "Ile iteracji Self-Refine jest optymalne?", options: ["1", "2-3", "10+", "Nie ma limitu"], correct: 1, explanation: "2-3 iteracje (generuj → krytykuj → popraw). Więcej = marginalne zyski." },
  { question: "Co jest kluczowe w multimodal prompting?", options: ["Używanie tylko obrazów bez tekstu", "Łączenie obrazu z kontekstem tekstowym i precyzyjnymi instrukcjami", "Wysyłanie jak największych plików", "Używanie wyłącznie GPT-4"], correct: 1, explanation: "Obraz + kontekst tekstowy + precyzyjne instrukcje = najlepsze wyniki." },

  // ─── SEMESTR IV: PIPELINE, WERYFIKACJA, PRODUKCJA (23-30) ──
  { question: "Dlaczego megaprompt jest gorszy niż chaining?", options: ["Bo jest za długi", "Bo model dzieli uwagę między wiele zadań i obniża jakość każdego", "Bo API odrzuca długie prompty", "Bo trwa dłużej"], correct: 1, explanation: "Model dzieli 'uwagę' na wiele zadań = spadek jakości. Chaining = 1 zadanie per krok = 95% jakości." },
  { question: "Co to jest Conditional Chaining?", options: ["Łączenie warunków w jednym prompcie", "Rozgałęzienie pipeline'u IF/ELSE na podstawie wyniku poprzedniego kroku", "Warunkowe generowanie odpowiedzi", "Chaining tylko gdy warunek spełniony"], correct: 1, explanation: "Conditional Chaining = inteligentne IF/ELSE w pipeline'ach promptów." },
  { question: "Co to jest Gate Keeping w pipeline?", options: ["Blokowanie dostępu do API", "Walidacja jakości między krokami — jeśli output słaby, powtórz", "Sprawdzanie uprawnień", "Filtrowanie tokenów"], correct: 1, explanation: "Gate Keeping sprawdza czy output spełnia wymagania przed kolejnym krokiem." },
  { question: "Na czym polega Self-Consistency?", options: ["Sprawdzanie gramatyki", "Generowanie wielu odpowiedzi i wybór najczęstszej/najspójniejszej", "Porównanie dwóch modeli", "Spójność ze stylem"], correct: 1, explanation: "Generuj 5 razy → porównaj → majority vote = wyższa dokładność." },
  { question: "Co oznacza Confidence Level: Medium w Self-Consistency?", options: ["1/5 odpowiedzi się zgadza", "3/5 odpowiedzi się zgadza", "5/5 odpowiedzi się zgadza", "Model jest pewny w 50%"], correct: 1, explanation: "High = 4-5/5, Medium = 3/5, Low = 2/5 zgodnych odpowiedzi." },
  { question: "Co to jest Verbose Mode w debugowaniu?", options: ["Dłuższe odpowiedzi", "Prośba by AI wyjaśniło jak zinterpretowało polecenie przed odpowiedzią", "Tryb głosowy", "Wyświetlanie tokenów"], correct: 1, explanation: "Verbose Mode pozwala zobaczyć czy model dobrze zrozumiał prompt." },
  { question: "Jak Prompt Caching obniża koszty?", options: ["Zapisuje odpowiedzi w przeglądarce", "Cache'uje powtarzalne części promptu — do 50% taniej", "Kompresuje tokeny", "Używa tańszego modelu"], correct: 1, explanation: "Powtarzalne system prompty/konteksty są cache'owane = 50% oszczędności na tych tokenach." },
  { question: "Ile razy profesjonalista iteruje prompt przed akceptacją?", options: ["1 raz", "3-5 razy", "20+ razy", "Nie iteruje — używa szablonów"], correct: 1, explanation: "3-5 iteracji z A/B testowaniem to standard profesjonalnego prompt engineeringu." },
];
