const { neon } = require("@neondatabase/serverless");
require("dotenv").config({ path: ".env.local" });

const sql = neon(process.env.DATABASE_URL);

async function updateOrInsert(slug, name, price_pln, type, description) {
  const existing = await sql`SELECT * FROM products WHERE slug = ${slug}`;
  if (existing.length > 0) {
    await sql`UPDATE products SET name = ${name}, price_pln = ${price_pln}, type = ${type}, description = ${description}, active = true WHERE slug = ${slug}`;
    console.log(`Updated ${slug} price to }{price_pln}`);
  } else {
    // Note: without 'id', assuming it has a default uuid_generate_v4() mapped locally or something similar! Let's check db schema!
    // Often it's generated by default. If not, we might need a library if it's missing. Let's try inserting without id.
    await sql`INSERT INTO products (slug, name, price_pln, type, active, description) VALUES (${slug}, ${name}, ${price_pln}, ${type}, true, ${description})`;
    console.log(`Inserted ${slug}`);
  }
}

async function main() {
  await updateOrInsert("basic", "Pakiet Basic", 9900, "bundle", "Podstawowy pakiet ze szkoleniem 1h");
  await updateOrInsert("pro", "Pakiet Pro", 39900, "bundle", "Pełny pakiet szkoleniowy");
  await updateOrInsert("meeting-addon", "Spotkanie Indywidualne", 14900, "course", "1.5h spotkanie online");
  await updateOrInsert("extra-training", "Dodatkowe Szkolenie", 6900, "course", "Kolejne szkolenie online 1h");

  await sql`UPDATE products SET active = false WHERE slug NOT IN ('basic', 'pro', 'meeting-addon', 'extra-training')`;
  console.log("Done");
}

main().catch(console.error);
